"use client";

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavbarComponent from "@/components/Navbar";
import {Providers} from "@/app/provider";

const inter = Inter({ subsets: ['latin'] })
import {NextUIProvider} from "@nextui-org/react";

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
        <html lang="en">
          <body className={inter.className}>
              <Providers themeProps={{ attribute: "class", defaultTheme: "dark" }}>
                  <NavbarComponent/>
                  {children}
              </Providers>
          </body>
        </html>
  )
}
